import { Pressable, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';

import { Field, PrimaryButton, SecondaryButton } from '../ui/FormControls';
import { styles } from '../../styles/appStyles';
import type { OperationalMobileItem } from '../../services/operationalMobileService';

type OperationalFormState = { codigo: string; descripcion: string; valor: string; observacion: string };

export function OperationalForm({ title, form, saving, onCancel, onChange, onSave }: { title: string; form: OperationalFormState; saving: boolean; onCancel: () => void; onChange: (field: keyof OperationalFormState, value: string) => void; onSave: () => void }) {
  return <View style={styles.formSectionBox}><Text style={styles.clientFormSubtitle}>Operacion</Text><Text style={styles.clientFormTitle}>{title}</Text><Field label="Codigo (opcional)" value={form.codigo} onChangeText={(value) => onChange('codigo', value)} autoCapitalize="characters" /><Field label="Descripcion *" value={form.descripcion} onChangeText={(value) => onChange('descripcion', value)} /><Field label="Valor / cantidad (opcional)" value={form.valor} onChangeText={(value) => onChange('valor', value)} keyboardType="decimal-pad" /><Field label="Observacion (opcional)" value={form.observacion} onChangeText={(value) => onChange('observacion', value)} /><View style={styles.formActions}><PrimaryButton label="Guardar" loading={saving} onPress={onSave} /><SecondaryButton label="Cancelar" onPress={onCancel} /></View></View>;
}

export function OperationalMobileItemCard({ item, canEdit, canDelete, onView, onEdit, onDelete }: { item: OperationalMobileItem; canEdit: boolean; canDelete: boolean; onView: () => void; onEdit: () => void; onDelete: () => void }) {
  return <View style={styles.crudCard}><View style={styles.clientCardHeader}><View style={styles.clientAvatar}><Text style={styles.clientAvatarText}>{(item.title || item.id || 'O').charAt(0).toUpperCase()}</Text></View><View style={styles.clientInfo}><Text style={styles.clientName}>{item.title || item.id}</Text>{item.subtitle ? <Text style={styles.clientMeta}>{item.subtitle}</Text> : null}</View>{item.status ? <View style={styles.systemPill}><Text style={styles.systemPillText}>{item.status}</Text></View> : null}</View><View style={styles.clientDetailGrid}>{item.meta ? <View style={styles.clientDetailItem}><Text style={styles.clientDetailLabel}>Dato</Text><Text style={styles.clientDetailValue}>{item.meta}</Text></View> : null}{item.detail ? <View style={styles.clientDetailItem}><Text style={styles.clientDetailLabel}>Detalle</Text><Text style={styles.clientDetailValue}>{item.detail}</Text></View> : null}</View><View style={styles.clientActions}><Pressable accessibilityRole="button" accessibilityLabel={`Ver ${item.title || item.id}`} style={[styles.smallActionButton, styles.crudViewAction]} onPress={onView}><MaterialCommunityIcons name="eye-outline" size={16} color="#00649D" /><Text style={styles.smallActionText}>Ver</Text></Pressable>{canEdit ? <Pressable accessibilityRole="button" accessibilityLabel={`Editar ${item.title || item.id}`} style={[styles.smallActionButton, styles.crudEditAction]} onPress={onEdit}><MaterialCommunityIcons name="pencil-outline" size={16} color="#6847FF" /><Text style={styles.crudEditText}>Editar</Text></Pressable> : null}{canDelete ? <Pressable accessibilityRole="button" accessibilityLabel={`Eliminar ${item.title || item.id}`} style={[styles.smallActionButton, styles.smallDangerButton]} onPress={onDelete}><MaterialCommunityIcons name="trash-can-outline" size={16} color="#B4232D" /><Text style={[styles.smallActionText, styles.smallDangerText]}>Eliminar</Text></Pressable> : null}</View></View>;
}
