import { StatusBar } from 'expo-status-bar';
import { ActivityIndicator, Image, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, Text, View } from 'react-native';
import { styles } from '../../styles/appStyles';
import { PrimaryButton } from '../ui/FormControls';

export function LoadingScreen() { return <View style={styles.loadingScreen}><View style={styles.loadingCard}><View style={styles.loadingIcon}><Text style={styles.loadingDigits}>= 4 =</Text><Text style={styles.loadingDigitsSmall}>7 · =</Text></View><Text style={styles.loadingTitle}>Validando Credenciales</Text><Text style={styles.loadingSubtitle}>Iniciando entorno seguro de Numérica...</Text><ActivityIndicator color="#6E94B4" style={styles.loadingSpinner} /></View><StatusBar style="light" /></View>; }
export function ScreenFrame({ children, centered }: { children: React.ReactNode; centered?: boolean }) { return <View style={styles.safeArea}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={Platform.OS === 'ios' ? 8 : 0} style={styles.flex}><ScrollView automaticallyAdjustKeyboardInsets contentContainerStyle={[styles.canvas, centered && styles.canvasCentered, styles.authScrollContent]} keyboardDismissMode="none" keyboardShouldPersistTaps="handled" nestedScrollEnabled showsVerticalScrollIndicator><View style={styles.blueGlow} />{children}</ScrollView></KeyboardAvoidingView><StatusBar style="light" backgroundColor="#07305E" translucent={false} /></View>; }
export function AuthCard({ children, wide, login }: { children: React.ReactNode; wide?: boolean; login?: boolean }) { return <View style={[styles.card, login && styles.loginCard, wide && styles.cardWide]}>{children}</View>; }
export function BrandMark() { return <View style={styles.logoBadge}><Image source={require('../../../assets/logo-numerica.png')} style={styles.logoImage} /></View>; }
export function BrandLockup() { return <View style={styles.brandLockup}><BrandMark /><Text style={styles.brandText}>Numérica{ '\n' }software</Text></View>; }
export function BiometricSetupModal({ label, onChoose }: { label: string; onChoose: (enable: boolean) => void }) { return <Modal transparent animationType="fade" statusBarTranslucent><View style={styles.biometricModalBackdrop}><View style={styles.biometricModalCard}><View style={styles.biometricModalIcon}><Text style={styles.biometricModalGlyph}>⌁</Text></View><Text style={styles.biometricModalTitle}>Acceso más rápido y seguro</Text><Text style={styles.biometricModalText}>Activa {label} para entrar a e-fact sin escribir tu contraseña la próxima vez.</Text><PrimaryButton label={`Activar ${label}`} loading={false} onPress={() => onChoose(true)} /><Pressable style={styles.biometricLaterButton} onPress={() => onChoose(false)}><Text style={styles.biometricLaterText}>Más tarde</Text></Pressable></View></View></Modal>; }
